---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ls-algorithm-webui
spec:
  selector:
    matchLabels:
      app: ls-algorithm-webui
  template:
    metadata:
      labels:
        app: ls-algorithm-webui
    spec:
      serviceAccountName: scaler-service-account
      containers:
        - name: ls-algorithm
          image: giovaz94/tea-store-ls
          imagePullPolicy: Always
          ports:
            - containerPort: 7001
          env:
            - name: SLEEP_TIME
              value: "10"
            - name: COMPONENT_MCL
              value: "150"
            - name: COMPONENT_MF
              value: "1"
            - name: K_BIG
              value: "35"
            - name: K
              value: "10"
            - name: IN_CLUSTER
              value: "true"
            - name: PROMETHEUS_SERVICE_ADDRESS
              value: "prometheus-service.monitoring.svc.cluster.local"
            - name: PROMETHEUS_SERVICE_PORT
              value: "8080"
            - name: MANIFEST_NAME
              value: "webui"
            - name: METRIC_NAME
              value: "http_requests_total_webUI_counter"
            - name: SERVICE_PORT
              value: "7000"
            
---
apiVersion: v1
kind: Service
metadata:
  name: ls-algorithm-webui-service
spec:
  selector:
    app: ls-algorithm-webui
  ports:
    - protocol: TCP
      port: 7000
      targetPort: 7000
