apiVersion: apps/v1
kind: Deployment
metadata:
  name: webui
spec:
  selector:
    matchLabels:
      app: webui
  template:
    metadata:
      labels:
        app: webui
    spec:
      containers:
      - name: webui
        image: giovaz94/tea-store-general
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: MCL
          value: "150"
        - name: SERVICE_NAME
          value: "webUI"
        - name: PORT
          value: "80"
        - name: KEEP_ALIVE
          value: "2500"
        - name: MAX_SIZE
          value: "200"
        - name: OUTPUT_SERVICES
          value: '{"http://persistence-ingress.default.svc.cluster.local/persistence/request":"1", "http://recommender-ingress.default.svc.cluster.local/recommender/request":"1", "http://image-ingress.default.svc.cluster.local/image/request":"2"}'
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: webui-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "80"
    prometheus.io/path: "/metrics"
spec:
  type: NodePort
  selector:
    app: webui
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 31000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webui-ingress
  annotations:
    traefik.ingress.kubernetes.io/load-balancer-method: "drr"
    # traefik.ingress.kubernetes.io/sticky: "true"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: webui-service
            port:
              number: 80