apiVersion: apps/v1
kind: Deployment
metadata:
  name: webui
spec:
  selector:
    matchLabels:
      app: webui
  template:
    metadata:
      labels:
        app: webui
    spec:
      containers:
        - name: webui
          image: giovaz94/tea-store-general 
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: MCL
              value: "150"
            - name: SERVICE_NAME
              value: "webUI"
            - name: PORT
              value: "80"
            - name: OUTPUT_SERVICES
              value: '{"http://persistence-service/request":"1", "http://recommender-service/request":"1", "http://image-service/request":"2"}'
      restartPolicy: Always
---
# apiVersion: v1
# kind: Service
# metadata:
#   name: webui-service
# spec:
#   selector:
#     app: webui
#   ports:
#     - protocol: TCP
#       port: 8001
#       targetPort: 8001
apiVersion: v1
kind: Service
metadata:
  name: webui-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "80"
    prometheus.io/path: "/metrics"   # optional, defaults to /metrics
spec:
  type: NodePort
  selector:
    app: webui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

