apiVersion: apps/v1
kind: Deployment
metadata:
  name: webUI
spec:
  selector:
    matchLabels:
      app: webUI
  template:
    metadata:
      labels:
        app: webUI
    spec:
      containers:
        - name: webUI
          image: giovaz94/tea-store-general
          imagePullPolicy: Always
          ports:
            - containerPort: 8001
          env:
            - name: MCL
              value: "150"
            - name: SERVICE_NAME
              value: "webUI"
            - name: PORT
              value: "8001"
            - name: OUTPUT_SERVICES
              value: '{"recommender":"http://recommender-service:8005/request","image":"http://image-service:8004/request","persistence":"http://persistence-service:8003/request","auth":"http://auth-service:8002/request"}'
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: webUI-service
spec:
  selector:
    app: webUI
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001

