apiVersion: apps/v1
kind: Deployment
metadata:
  name: webui
spec:
  selector:
    matchLabels:
      app: webui
  template:
    metadata:
      labels:
        app: webui
    spec:
      containers:
      - name: webui
        image: giovaz94/tea-store-general
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
          - name: MCL
            value: "150"
          - name: SERVICE_NAME
            value: "webUI"
          - name: PORT
            value: "80"
          - name: MAX_SIZE
            value: "1000"
          - name: OUTPUT_SERVICES
            value: '{"http://persistence-service/request":"1", "http://recommender-service/request":"1", "http://image-service/request":"2"}'
          - name: MAX_CONNECTIONS
            value: "70"
          - name: PIPELINE_COUNT
            value: "1"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: webui-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "80"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: webui
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: webui-service
spec:
spec:
  host: webui-service
  trafficPolicy:
    loadBalancer:
      simple: LEAST_REQUEST
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: webui-service
spec:
  hosts:
    - webui-service
  http:
    - route:
        - destination:
            host: webui-service
