---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ls-algorithm-auth
spec:
  selector:
    matchLabels:
      app: ls-algorithm-auth
  template:
    metadata:
      labels:
        app: ls-algorithm-auth
    spec:
      serviceAccountName: ls-service-account
      containers:
        - name: ls-algorithm
          image: giovaz94/local_scaling
          imagePullPolicy: Always
          ports:
            - containerPort: 7001
          env:
            - name: SLEEP_TIME
              value: "10"
            - name: COMPONENT_MCL
              value: "190"
            - name: COMPONENT_MF
              value: "1"
            - name: K_BIG
              value: "10"
            - name: K
              value: "8"
            - name: IN_CLUSTER
              value: "true"
            - name: PROMETHEUS_SERVICE_ADDRESS
              value: "prometheus-service.monitoring"
            - name: PROMETHEUS_SERVICE_PORT
              value: "8080"
            - name: MANIFEST_NAME
              value: "auth"
            - name: METRIC_NAME
              value: "http_requests_total_attachment_manager_counter" #TODO CHANGE THIS
            - name: SERVICE_PORT
              value: "7001"
            
---
apiVersion: v1
kind: Service
metadata:
  name: ls-algorithm-auth-service
spec:
  selector:
    app: ls-algorithm-auth
  ports:
    - protocol: TCP
      port: 7001
      targetPort: 7001
