apiVersion: v1
kind: Pod
metadata:
  generateName: sys-pod-image-
  labels:
    app: image
spec:
  containers:
    - name: image
      image: giovaz94/tea-store-general 
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
      env:
        - name: MCL
          value: "600"
        - name: SERVICE_NAME
          value: "image"
        - name: MAX_SIZE
          value: "1500000"
        - name: PORT
          value: "80"
        - name: OUTPUT_SERVICES
          value: '{}'
        - name: MAX_CONNECTIONS
          value: "70"
        - name: PIPELINE_COUNT
          value: "1"
  restartPolicy: Always