apiVersion: v1
kind: Pod
metadata:
  generateName: sys-pod-message-analyzer-
  labels:
    app: message-analyzer
spec:
  #nodeName: testing-cluster-pool-b7x6f
  containers:
  - name: message-analyzer
    image: giovaz94/message-analyzer-service
    env:
      - name: REDIS_HOST
        value: "redis-service"
      - name: MCL
        value: "300"
      - name: LIMIT
        value: "800"
      - name: DELAY
        value: "750"
      - name: BATCH
        value: "300"