---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ls-algorithm-persistence
spec:
  selector:
    matchLabels:
      app: ls-algorithm-persistence
  template:
    metadata:
      labels:
        app: ls-algorithm-persistence
    spec:
      serviceAccountName: scaler-service-account
      containers:
        - name: ls-algorithm
          image: giovaz94/tea-store-ls
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7002
          env:
            - name: SLEEP_TIME
              value: "20"
            - name: COMPONENT_MCL
              value: "905"
            - name: COMPONENT_MF
              value: "4"
            - name: K_BIG
              value: "10"
            - name: K
              value: "5"
            - name: IN_CLUSTER
              value: "true"
            - name: PROMETHEUS_SERVICE_ADDRESS
              value: "prometheus-service.monitoring.svc.cluster.local"
            - name: PROMETHEUS_SERVICE_PORT
              value: "8080"
            - name: MANIFEST_NAME
              value: "persistence"
            - name: METRIC_NAME
              value: "http_requests_total_persistence_counter"
            - name: SERVICE_PORT
              value: "7002" 
            
---
apiVersion: v1
kind: Service
metadata:
  name: ls-algorithm-persistence-service
spec:
  selector:
    app: ls-algorithm-persistence
  ports:
    - protocol: TCP
      port: 7002
      targetPort: 7002
