apiVersion: apps/v1
kind: Deployment
metadata:
  name: persistence
spec:
  selector:
    matchLabels:
      app: persistence
  template:
    metadata:
      labels:
        app: persistence
    spec:
      containers:
        - name: persistence
          image: giovaz94/tea-store-general 
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: MCL
              value: "905"
            - name: SERVICE_NAME
              value: "persistence"
            - name: PORT
              value: "80"
            - name: MAX_SIZE
              value: "150"
            - name: OUTPUT_SERVICES
              value: '{}'
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: persistence-service
  annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "80"
      prometheus.io/path: "/metrics"   # optional, defaults to /metrics
spec:
  selector:
    app: persistence
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

