---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ls-algorithm-recommender
spec:
  selector:
    matchLabels:
      app: ls-algorithm-recommender
  template:
    metadata:
      labels:
        app: ls-algorithm-recommender
    spec:
      serviceAccountName: scaler-service-account
      containers:
        - name: ls-algorithm
          image: giovaz94/tea-store-ls
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7005
          env:
            - name: SLEEP_TIME
              value: "20"
            - name: COMPONENT_MCL
              value: "5000"
            - name: COMPONENT_MF
              value: "3"
            - name: K_BIG
              value: "10"
            - name: K
              value: "10"
            - name: IN_CLUSTER
              value: "true"
            - name: PROMETHEUS_SERVICE_ADDRESS
              value: "prometheus-service.monitoring.svc.cluster.local"
            - name: PROMETHEUS_SERVICE_PORT
              value: "8080"
            - name: MANIFEST_NAME
              value: "recommender"
            - name: METRIC_NAME
              value: "http_requests_total_recommender_counter"
            - name: SERVICE_PORT
              value: "7005"
            
---
apiVersion: v1
kind: Service
metadata:
  name: ls-algorithm-recommender-service
spec:
  selector:
    app: ls-algorithm-recommender
  ports:
    - protocol: TCP
      port: 7005
      targetPort: 7005
