apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommender
spec:
  selector:
    matchLabels:
      app: recommender
  template:
    metadata:
      labels:
        app: recommender
    spec:
      containers:
        - name: recommender
          recommender: giovaz94/tea-store-general
          recommenderPullPolicy: Always
          ports:
            - containerPort: 8005
          env:
            - name: MCL
              value: "190"
            - name: SERVICE_NAME
              value: "recommender"
            - name: PORT
              value: "8005"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: recommender-service
spec:
  selector:
    app: recommender
  ports:
    - protocol: TCP
      port: 8005
      targetPort: 8005

