apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommender
spec:
  selector:
    matchLabels:
      app: recommender
  template:
    metadata:
      labels:
        app: recommender
    spec:
      containers:
        - name: recommender
          image: giovaz94/tea-store-general
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: MCL
              value: "190"
            - name: SERVICE_NAME
              value: "recommender"
            - name: PORT
              value: "80"
            - name: OUTPUT_SERVICES
              value: '{}'
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: recommender-service
spec:
  selector:
    app: recommender
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

