apiVersion: apps/v1
kind: Deployment
metadata:
  name: entrypoint
  labels:
    app: entrypoint
spec:
  replicas: 1
  selector:
    matchLabels:
      app: entrypoint
  template:
    metadata:
      labels:
        app: entrypoint
    spec:
      containers:
        - name: entrypoint
          image: giovaz94/tea-store-ep
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: PORT
              value: "80"
            - name: ENDPOINT
              value: "http://webui-service/request"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: entrypoint
  name: entrypoint-service
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: entrypoint