apiVersion: apps/v1
kind: Deployment
metadata:
  name: entrypoint
  labels:
    app: entrypoint
spec:
  replicas: 1
  selector:
    matchLabels:
      app: entrypoint
  template:
    metadata:
      labels:
        app: entrypoint
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: entrypoint
          image: giovaz94/entrypoint
          imagePullPolicy: Always
          ports:
            - containerPort: 8010
          env:
            - name: PORT
              value: "8010"
            - name: REFRESH_TIME
              value: "300000"
            - name: LS_ENABLED
              value: "true"
            - name: REDIS_HOST
              value: "redis-service"
            - name: LIMIT
              value: "8000"
          resources:
            requests:
              cpu: 100m
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: entrypoint
  name: entrypoint-service
spec:
  ports:
    - port: 8010
      targetPort: 8010
      protocol: TCP
      nodePort: 30080
  selector:
    app: entrypoint
  type: NodePort