--- 
apiVersion: batch/v1
kind: CronJob
metadata:
  name: eta-checker
  namespace: default
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          serviceAccountName: scaler-service-account-cluster
          restartPolicy: OnFailure
          containers:
            - name: eta-checker
              image: giovaz94/tea-store-cj
              imagePullPolicy: IfNotPresent
              env:
                - name: TZ
                  value: UTC
                - name: POD_AGE_LIMIT
                  value: "100"