apiVersion: batch/v1
kind: Job
metadata:
  name: goose-loadtest
spec:
  template:
    spec:
      containers:
      - name: goose
        image: giovaz94/goose-service
        imagePullPolicy: Always
      restartPolicy: Never
  backoffLimit: 1