apiVersion: apps/v1
kind: Deployment
metadata:
  name: image
spec:
  replicas: 2
  selector:
    matchLabels:
      app: image
  template:
    metadata:
      labels:
        app: image
    spec:
      containers:
        - name: image
          image: giovaz94/tea-store-general 
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: MCL
              value: "600"
            - name: SERVICE_NAME
              value: "image"
            - name: MAX_SIZE
              value: "200"
            - name: PORT
              value: "80"
            - name: OUTPUT_SERVICES
              value: '{}'
            - name: MAX_CONNECTIONS
              value: "70"
            - name: PIPELINE_COUNT
              value: "1"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: image-service
  annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "80"
      prometheus.io/path: "/metrics"
spec:
  selector:
    app: image
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: image-service
spec:
  host: image-service
  trafficPolicy:
    loadBalancer:
      simple: LEAST_REQUEST
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: image-service
spec:
  hosts:
    - image-service
  http:
    - route:
        - destination:
            host: image-service