---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ls-algorithm-image
spec:
  selector:
    matchLabels:
      app: ls-algorithm-image
  template:
    metadata:
      labels:
        app: ls-algorithm-image
    spec:
      serviceAccountName: scaler-service-account
      containers:
        - name: ls-algorithm
          image: giovaz94/tea-store-ls
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7003
          env:
            - name: SLEEP_TIME
              value: "20"
            - name: COMPONENT_MCL
              value: "600"
            - name: COMPONENT_MF
              value: "6"
            - name: K_BIG
              value: "10"
            - name: K
              value: "5"
            - name: IN_CLUSTER
              value: "true"
            - name: PROMETHEUS_SERVICE_ADDRESS
              value: "prometheus-service.monitoring.svc.cluster.local"
            - name: PROMETHEUS_SERVICE_PORT
              value: "8080"
            - name: MANIFEST_NAME
              value: "image"
            - name: METRIC_NAME
              value: "http_requests_total_image_counter"
            - name: SERVICE_PORT
              value: "7003"
            - name: MIN_INST
              value: "2"

            
---
apiVersion: v1
kind: Service
metadata:
  name: ls-algorithm-image-service
spec:
  selector:
    app: ls-algorithm-image
  ports:
    - protocol: TCP
      port: 7003
      targetPort: 7003
