apiVersion: apps/v1
kind: Deployment
metadata:
  name: gs-algorithm
spec:
  selector:
    matchLabels:
      app: gs-algorithm
  template:
    metadata:
      labels:
        app: gs-algorithm
    spec:
      serviceAccountName: gs-service-account
      containers:
        - name: gs-algorithm
          image: giovaz94/tea-store-gs
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: INCLUSTER_CONFIG
              value: "true"
            - name: K_BIG
              value: "35"
            - name:  SLEEP
              value: "10"
            - name: K
              value: "10"
            - name: ERROR_LIMIT
              value: "3"
            - name: PROACTIVE
              value: "false"
            - name: PROACTIVE_REACTIVE
              value: "false"
            - name: PROMETHEUS_SERVICE_ADDRESS
              value: "prometheus-service.monitoring.svc.cluster.local"
            - name: PROMETHEUS_SERVICE_PORT
              value: "8080"
            - name: MONITOR_ONLY
              value: "true"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: gs-algorithm-service
spec:
  selector:
    app: gs-algorithm
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000