apiVersion: v1
kind: Pod
metadata:
  generateName: sys-pod-webui-
  labels:
    app: webui
spec:
  containers:
    - name: webui
      image: giovaz94/tea-store-general 
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
      env:
        - name: MCL
          value: "150"
        - name: SERVICE_NAME
          value: "webUI"
        - name: PORT
          value: "80"
        - name: MAX_SIZE
          value: "150"
        - name: OUTPUT_SERVICES
          value: '{"http://persistence-service/request":"1", "http://recommender-service/request":"1", "http://image-service/request":"2"}'
  restartPolicy: Always