apiVersion: v1
kind: Pod
metadata:
  generateName: sys-pod-persistence-
  labels:
    app: persistence
spec:
  containers:
    - name: persistence
      image: giovaz94/tea-store-general 
      imagePullPolicy: Always
      ports:
        - containerPort: 80
      env:
        - name: MCL
          value: "905"
        - name: SERVICE_NAME
          value: "persistence"
        - name: PORT
          value: "80"
        - name: MAX_SIZE
          value: "50"
        - name: OUTPUT_SERVICES
          value: '{}'
  restartPolicy: Always