apiVersion: v1
kind: Pod
metadata:
  generateName: sys-pod-auth-
  labels:
    app: auth
spec:
  containers:
    - name: auth
      image: giovaz94/tea-store-general 
      imagePullPolicy: Always
      ports:
        - containerPort: 80
      env:
        - name: MCL
          value: "190"
        - name: SERVICE_NAME
          value: "auth"
        - name: PORT
          value: "80"
        - name: MAX_SIZE
          value: "200"
        - name: OUTPUT_SERVICES
          value: '{"http://persistence-service/request":"1"}'
  restartPolicy: Always