name: Build & Publish Docker images
on:
  push:
    branches:
      - main

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./entrypoint/Dockerfile
            context: ./entrypoint
            image: giovaz94/tea-store-ep
          - dockerfile: ./global-scaler/Dockerfile
            context: ./global-scaler
            image: giovaz94/tea-store-gs
          - dockerfile: ./local-scaling/Dockerfile
            context: ./local-scaling
            image: giovaz94/tea-store-ls
          - dockerfile: ./service/Dockerfile
            context: ./service
            image: giovaz94/tea-store-general
          
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push on Docker hub
        uses: docker/build-push-action@v3
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ matrix.image }}:latest